version: '3.5'
services: # Here we define our service(s)
  mysql-db:
    # restart: always
    image: mysql:latest
    container_name: mysql  # Container name
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: sys
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ROOT_HOST: '%'
    # volumes:
    #   - my-datavolume:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  angular-service: # The name of the service
    container_name: cplayer-angular  # Container name
    build: ./CPlayersUI # Location of our Dockerfile
    volumes: # Volume binding
      - './CPlayersUI:/usr/src/app'
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  user-api:
    restart: on-failure:5
    build: ./userservice
    ports:
      - 8050:8050
    environment:
      WAIT_HOSTS: mysql:3306
      # SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CMATCH?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-db
  favourite-api:
    restart: on-failure:5
    build: ./favouriteservice
    ports:
      - 8051:8051
    environment:
      WAIT_HOSTS: mysql:3306
      # SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CMATCH?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-db
# volumes:
#   my-datavolume: